name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable Corepack (pnpm)
        run: |
          corepack enable
          corepack prepare pnpm@10.30.3 --activate
          pnpm --version

      - name: Install deps
        working-directory: web
        run: pnpm install --frozen-lockfile

      - name: Lint
        working-directory: web
        run: pnpm lint

      - name: Build
        working-directory: web
        run: pnpm build
